apiVersion: v1
kind: Pod
metadata:
  name: multi-container-demo
spec:
  # Shared storage for both containers
  volumes:
  - name: log-storage
    emptyDir: {}

  containers:
  # Container 1: The "Producer" (Simulates an app writing logs)
  - name: app-container
    image: busybox
    command: ["sh", "-c", "while true; do date >> /var/log/app.log; sleep 5; done"]
    volumeMounts:
    - name: log-storage
      mountPath: /var/log

  # Container 2: The "Sidecar" (Simulates a log processor)
  - name: sidecar-container
    image: busybox
    command: ["sh", "-c", "tail -f /var/log/app.log"]
    volumeMounts:
    - name: log-storage
      mountPath: /var/log