apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-pod
spec:
  volumes:
    - name: secret-vol
      secret:
        secretName: app-db-secret
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
      - name: secret-vol
        mountPath: "/etc/db-creds"
        readOnly: true