apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo 'Password is set' && sleep 3600"]
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: app-db-secret
            key: password