apiVersion: v1
kind: Pod
metadata:
  name: tolerated-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
  tolerations:
  - key: "department"
    operator: "Equal"
    value: "finops"
    effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: minikube-m02