apiVersion: v1
kind: Pod
metadata:
  name: ssd-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo 'I am on the SSD node'; sleep 3600"]
  nodeSelector:
    disktype: ssd