apiVersion: v1
kind: Pod
metadata:
  name: prod-affinity-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - prod
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo 'I am in the prod zone'; sleep 3600"]